apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payment-service-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: payment-service-secret
    creationPolicy: Owner
  data:
    - secretKey: PAYMENT_API_KEY
      remoteRef:
        key: payment-service/prod
        property: paymentApiKey
